version: '3.8'
services:
  nginx:
    image: nginx:1.25.3-alpine-slim
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
    healthcheck:
      test: service nginx status || exit 1
      start_period: 10s
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/logthemis.ase.cit.tum.de80:/etc/nginx/sites-enabled/logthemis.ase.cit.tum.de80:ro
      - ./config/nginx/logthemis.ase.cit.tum.de443:/etc/nginx/sites-enabled/logthemis.ase.cit.tum.de443:ro
      - type: bind
        source: '/var/lib/rbg-cert/live/host:f:logthemis.ase.cit.tum.de.fullchain.pem'
        target: '/certs/fullchain.pem'
      - type: bind
        source: '/var/lib/rbg-cert/live/host:f:logthemis.ase.cit.tum.de.privkey.pem'
        target: '/certs/privkey.pem'
  logthemis:
    build: "."
    expose:
      - "5000"
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - "./config/logthemis.env"
    volumes:
      - "./data/logs:/app/data/logs:ro"
      - "./data/db:/app/data/db"